name: Generate Contribution Breakout Game

on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Generate breakout game
        uses: cyprieng/github-breakout@v1
        with:
          github_username: kashewknutt
          theme: dark
          output_path: dist

      - name: Commit and push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add dist
          git commit -m "Update breakout game" || echo "No changes"
          git push
